### ISSUE TITLE
没想到你又搞petpc版了，怎么不在vue/pet继续啊？

### ISSUE THREAD

**Issue by baruide** [jamielhf/petpc#1]
看你之前的vue项目写的很好，虽然我看不太懂（QAQ）,因为你我也才使用了mockjs。所以很期待你能在那个项目上继续搞啊！

这个项目你主要搞服务器方面的是吗？node 和mongoose也是小白啊，我估计是看不懂啦。

加油！ commit时候能多些写字就更好了。

**Comment by jamielhf** [comment]
好的，因为工作的问题，所以最近更新不是很多，谢谢建议哈
